### ISSUE TITLE
.Site.GetPage "taxonomyTerm" "authors" turns to error 

### ISSUE THREAD

**Issue by yudyananda** [imorente/hugo-multiauthor-example#1]
Hi there

I have plans to use the latest Hugo version, but it seems I have to postpone it because I have problems when implementing multi-author.

I'm not sure but maybe this cause the error 

```
 error calling GetPage: too many arguments to .Site.GetPage: [taxonomyTerm authors Nurul Hidayani]. Use lookups on the form {{ .Site.GetPage "/posts/mypage-md" }}
```

is it possible that this is caused by changes in version 0.45?

**Comment by imorente** [comment]
> is it possible that this is caused by changes in version 0.45?

It certainly is! (
https://gohugo.io/functions/getpage/). A quick fix is to change the way author pages are looked up in the `author-figure.html` template: https://github.com/imorente/hugo-multiauthor-example/pull/2/files#diff-426c4aae705cdcfd6ad9db010987db5bR2

I'll try to fix this in a way that works in both older and newer versions of Hugo. Thanks for pointing it out!
